name: spendable
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54323:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
